name: Build and Deploy to Docker Hub

on:
  push:
    branches:
      - main

env:
  DOCKER_IMAGE: mahendra968/mahendra2
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}

    - name: Deploy to Remote Server (VM)
      run: |
        ssh -o StrictHostKeyChecking=no -i ${{ secrets.SSH_PRIVATE_KEY }} mahendra@172.25.1.112"
          docker pull $DOCKER_IMAGE:${{ env.IMAGE_TAG }} &&
          docker stop your-container-name || true &&
          docker rm your-container-name || true &&
          docker run -d --name deploy1 $DOCKER_IMAGE:${{ env.IMAGE_TAG }}"
