name: Build and Deploy to Kubernetes

on:
  push:
    branches: [ main ]

env:
  DOCKER_IMAGE: mahendra968/mahendra2
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ env.DOCKER_IMAGE }}:${{ env.IMAGE_TAG }}
    
    - name: Setup kubectl
      uses: azure/setup-kubectl@v1
    
    - name: Create kubeconfig
      run: |
        mkdir -p $HOME/.kube
        cat > $HOME/.kube/config <<EOF
        apiVersion: v1
        kind: Config
        clusters:
        - cluster:
            certificate-authority-data: ${{ secrets.KUBE_CA_DATA }}
            server: ${{ secrets.KUBE_API_URL }}
          name: my-cluster
        contexts:
        - context:
            cluster: my-cluster
            user: github-actions
          name: my-cluster-context
        current-context: my-cluster-context
        users:
        - name: github-actions
          user:
            token: ${{ secrets.KUBE_TOKEN }}
        EOF
        chmod 600 $HOME/.kube/config
    
    - name: Deploy to Kubernetes
      run: |
        sed -i "s|\${DOCKER_IMAGE}|$DOCKER_IMAGE|g" k8s/deployment.yaml
        sed -i "s|\${IMAGE_TAG}|$IMAGE_TAG|g" k8s/deployment.yaml
        
        kubectl apply -f k8s/deployment.yaml --validate=false
        kubectl apply -f k8s/service.yaml --validate=false